#!/bin/bash
set -e
BASE=$0
BASE_PATH=$(dirname $BASE)

$BASE_PATH/backup-env.sh
if [ "$RESTORE" = "YES" ]; then
    $BASE_PATH/restore.sh
else
    $BASE_PATH/postgres.sh
fi

# TODO Utiliser le système d'INIT de l'image
sudo -u postgres /usr/lib/postgresql/9.4/bin/postgres -D "$PGDATA" -c config_file=/etc/postgresql/9.4/main/postgresql.conf

