FROM quay.io/pires/docker-elasticsearch-kubernetes:2.3.4

RUN /elasticsearch/bin/plugin install jettro/elasticsearch-gui --verbose && /elasticsearch/bin/plugin install lmenezes/elasticsearch-kopf/v2.1.2 --verbose
